### ISSUE TITLE
Convince Dagger to support automatic module discovery in a general way

### ISSUE THREAD

**Issue by JakeWharton** [square/AssistedInject#23]
We've now hit the rule of three with public use cases for this feature:

 * `@ContributesAndroidInjector`
 * `@AssistedInject`
 * `@InflationInject`

The first one has _massively_ superior ergonomics because its generated bindings can be auto-discovered and bound into the graph. It gets this by virtue of being built by the Dagger team. Lucky! 

The latter two are in this repo and do not receive auto-discovery. Instead, we force the consumers to annotate a module such that we generate a sibling module which contains only unscoped bindings. This lets us talk to Dagger where we otherwise cannot. It has devastating effects on incremental compilation and incremental annotation processing since both need to aggregate all usages in a compilation unit. And finally, it has annoying ergonomics because you have to reference generated code directly and manually include a module.

An additional hypothetic use case as well as the general Dagger feature request is tracked here: https://github.com/google/dagger/issues/869. This also would eliminate the need for Dagger to build everything as a first-party feature (e.g., https://github.com/google/dagger/issues/935) and allow people to mix-in behavior from other libraries.

We should come up with a proposal for the general mechanism on which Dagger's `@ContributesAndroidInjector` and our `@AssistedInject` and `@InflationInject` can be built.

**Comment by ronshapiro** [comment]
I noticed the same thing today. I'm game to discuss

**Comment by JakeWharton** [comment]
Oh, hello! I wanted to gather a good argument and possible proposal to make sure this can even be done properly before I sent it to you all. But I'm of course happy to have you involved as early as possible if you're willing.

**Comment by filipkowicz** [comment]
Do you have any update from Dagger side?

**Comment by JakeWharton** [comment]
FYI: https://github.com/google/dagger/issues/1825

**Comment by JakeWharton** [comment]
Here's what's going to happen.

**Phase 1:**

 1. [ ] Do not wrap Dagger `@AssistedFactory` types in a `Provider` when used in our `@AssistedInject` or `@InflationInject` constructors because this is an error. (#164)
 2. [ ] Move `@AssistedInject.Factory` to `@AssistedFactory` for parity with Dagger. This dramatically eases migration since you can do a simple find/replace on imports.

Release minor version.

**Phase 2:**

 1. [ ] Migrate `@InflationInject` to its own `@Inflated` to replace `@Assisted`. Dagger will not let us use its `@Assisted` without erroring and two types with the same simple name suck.
 2. [ ] Demolish all assisted injection support.
 3. [ ] Rename project to InflationInject.

Release 1.0.
